import io
from datetime import datetime


def generate_text_report(eval_result: dict) -> str:
    """Generate a plain-text audit report suitable for download."""
    lines = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines.append("=" * 70)
    lines.append("AI GOVERNANCE AUDIT REPORT")
    lines.append(f"Generated: {now}")
    lines.append("Framework: NIST AI RMF + HIPAA Healthcare Lens")
    lines.append("=" * 70)
    lines.append("")
    lines.append("USE CASE")
    lines.append("-" * 40)
    lines.append(eval_result["use_case"])
    lines.append("")
    lines.append("OVERALL GOVERNANCE SCORE")
    lines.append("-" * 40)
    lines.append(f"Score:    {eval_result['overall_pct']}%")
    lines.append(f"Maturity: {eval_result['maturity_label']}")
    lines.append(f"Summary:  {eval_result['maturity_desc']}")
    lines.append("")

    if eval_result["critical_items"]:
        lines.append("⚠  CRITICAL BLOCKERS (address before any deployment)")
        lines.append("-" * 40)
        for r in eval_result["critical_items"]:
            lines.append(f"  [{r['id']}] {r['name']}")
            lines.append(f"  Rationale:   {r['rationale']}")
            lines.append(f"  Remediation: {r['remediation']}")
            lines.append("")

    for label, items in [
        ("RED — High Risk (score 1–2)", eval_result["red_items"]),
        ("AMBER — Moderate Risk (score 3)", eval_result["amber_items"]),
        ("GREEN — Adequate (score 4–5)", eval_result["green_items"]),
    ]:
        lines.append(label)
        lines.append("-" * 40)
        for r in items:
            lines.append(f"  [{r['id']}] {r['name']}  —  Score: {r['score']}/5  |  {r['function']}")
            lines.append(f"  {r['rationale']}")
            if r["remediation"]:
                lines.append(f"  → {r['remediation']}")
            lines.append("")

    lines.append("=" * 70)
    lines.append("END OF REPORT")
    lines.append("Generated by AI Governance Audit Tool | github.com/zabeelbasheer/ai-governance-audit-tool")

    return "\n".join(lines)
